In [21]:
import pandas as pd
df=pd.read_csv('H:\\data_science\\creditcard.csv')
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [22]:
df['Class'].value_counts()



0    284315
1       492
Name: Class, dtype: int64

In [23]:
df.shape

(284807, 31)

In [24]:
df=df.fillna(df.mean())

#### Independent and Dependent Features
X=df.drop("Class",axis=1)
y=df.Class

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV



In [25]:
10.0 **np.arange(-2,3)

log_class=LogisticRegression()
grid={'C':10.0 **np.arange(-2,3),'penalty':['l1','l2']}
cv=KFold(n_splits=5,random_state=None,shuffle=False)






In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7)



In [27]:
clf=GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro')
clf.fit(X_train,y_train)





C:\Users\Dell\anaconda3\envs\testing\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Dell\anaconda3\envs\testing\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Dell\anaconda3\envs\testing\lib\site-packages\sklearn\linear_model\_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\Dell\anaconda3\envs\testing\lib\site-packages\sklearn\linear_model\_logistic.py", line 

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [28]:
y_pred=clf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85260    45]
 [   56    82]]
0.9988179254005595
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85305
           1       0.65      0.59      0.62       138

    accuracy                           1.00     85443
   macro avg       0.82      0.80      0.81     85443
weighted avg       1.00      1.00      1.00     85443



In [29]:


class_weight=dict({0:1,1:100})



In [30]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(class_weight=class_weight)
classifier.fit(X_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [31]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85302     3]
 [   27   111]]
0.9996488887328394
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85305
           1       0.97      0.80      0.88       138

    accuracy                           1.00     85443
   macro avg       0.99      0.90      0.94     85443
weighted avg       1.00      1.00      1.00     85443



In [32]:
pip install imblearn


In [33]:
!pip install --upgrade scikit-learn
!pip install --upgrade imblearn

In [34]:
pip install imblearn

Note: you may need to restart the kernel to use updated packages.


In [35]:

from collections import Counter
from imblearn.under_sampling import NearMiss
ns = NearMiss(sampling_strategy=0.8)
X_train_ns,y_train_ns=ns.fit_resample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

The number of classes before fit Counter({0: 199010, 1: 354})
The number of classes after fit Counter({0: 442, 1: 354})


In [36]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)



RandomForestClassifier()

In [37]:


y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))



[[68728 16577]
 [    9   129]]
0.80588228409583
              precision    recall  f1-score   support

           0       1.00      0.81      0.89     85305
           1       0.01      0.93      0.02       138

    accuracy                           0.81     85443
   macro avg       0.50      0.87      0.45     85443
weighted avg       1.00      0.81      0.89     85443



In [38]:
from imblearn.over_sampling import RandomOverSampler

In [40]:
os=RandomOverSampler(sampling_strategy=0.75)
X_train_ns,y_train_ns=os.fit_resample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))



The number of classes before fit Counter({0: 199010, 1: 354})
The number of classes after fit Counter({0: 199010, 1: 149257})


In [41]:

from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)



RandomForestClassifier()

In [42]:


y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))



[[85304     1]
 [   24   114]]
0.9997074072773662
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85305
           1       0.99      0.83      0.90       138

    accuracy                           1.00     85443
   macro avg       1.00      0.91      0.95     85443
weighted avg       1.00      1.00      1.00     85443



In [43]:
from imblearn.combine import SMOTETomek

In [46]:
os=SMOTETomek(sampling_strategy=0.75)
X_train_ns,y_train_ns=os.fit_resample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

The number of classes before fit Counter({0: 199010, 1: 354})
The number of classes after fit Counter({0: 198163, 1: 148410})


In [47]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [48]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85292    13]
 [   24   114]]
0.9995669627705019
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85305
           1       0.90      0.83      0.86       138

    accuracy                           1.00     85443
   macro avg       0.95      0.91      0.93     85443
weighted avg       1.00      1.00      1.00     85443



In [49]:
from imblearn.ensemble import EasyEnsembleClassifier

In [50]:
easy=EasyEnsembleClassifier()


In [51]:
easy.fit(X_train,y_train)

EasyEnsembleClassifier()

In [52]:
y_pred=easy.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[82695  2610]
 [   12   126]]
0.9693128752501667
              precision    recall  f1-score   support

           0       1.00      0.97      0.98     85305
           1       0.05      0.91      0.09       138

    accuracy                           0.97     85443
   macro avg       0.52      0.94      0.54     85443
weighted avg       1.00      0.97      0.98     85443

